"""Regenerate public/fonts/ from Google Fonts.

Liquid Glass fetches and base64-inlines every @font-face it can see before it
renders its first frame, so remote fonts stall the effect for seconds on a cold
or offline start. Keeping the woff2 files local makes that step instant.

Run from the repo root after changing FAMILIES:

    python scripts/fetch-fonts.py

Only the `latin` subset is kept (it covers German umlauts and ß). Variable
fonts return the same file for every weight, so identical files are deduped.
"""

import collections
import hashlib
import pathlib
import re
import urllib.request

FAMILIES = [
    "Inter:wght@400;500;600",
    "Instrument+Serif:ital@0;1",
    "Caveat:wght@400;500;600",
    "Bricolage+Grotesque:opsz,wght@12..96,400;12..96,600;12..96,800",
    "Manrope:wght@400;500;600;700",
]
# Google serves woff2 only to browsers it recognises.
CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)
OUT_DIR = pathlib.Path("public/fonts")


def fetch(url, user_agent=None):
    request = urllib.request.Request(url)
    if user_agent:
        request.add_header("User-Agent", user_agent)
    return urllib.request.urlopen(request).read()


def main():
    css_url = (
        "https://fonts.googleapis.com/css2?"
        + "&".join(f"family={family}" for family in FAMILIES)
        + "&display=swap"
    )
    css = fetch(css_url, CHROME_UA).decode("utf-8")

    blocks = re.findall(r"(/\*\s*([a-z0-9-]+)\s*\*/\s*@font-face\s*\{[^}]*\})", css)
    latin = [block for block, subset in blocks if subset == "latin"]
    if not latin:
        raise SystemExit("No latin @font-face blocks found — did the CSS format change?")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for stale in OUT_DIR.glob("*.woff2"):
        stale.unlink()

    rendered = []
    by_hash = collections.OrderedDict()
    for block in latin:
        family = re.search(r"font-family:\s*'([^']+)'", block).group(1)
        weight = re.search(r"font-weight:\s*([^;]+);", block).group(1).strip().replace(" ", "")
        style = re.search(r"font-style:\s*([^;]+);", block).group(1).strip()
        url = re.search(r"url\((https://[^)]+)\)", block).group(1)

        data = fetch(url)
        digest = hashlib.sha256(data).hexdigest()
        name = by_hash.get(digest)
        if name is None:
            name = f"{family.replace(' ', '')}-{weight}-{style}.woff2"
            (OUT_DIR / name).write_bytes(data)
            by_hash[digest] = name
        rendered.append(block.replace(url, f"/fonts/{name}"))

    header = (
        "/* Generated by scripts/fetch-fonts.py — do not edit by hand.\n"
        "   Self-hosted latin subsets of the Google Fonts the app uses. */\n"
    )
    with open(OUT_DIR / "fonts.css", "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header + "\n".join(rendered) + "\n")

    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))
    print(f"{len(by_hash)} files, {total:,} bytes, {len(rendered)} @font-face rules")


if __name__ == "__main__":
    main()
